// The generator (ABI-1, AUT-3): reflect each endpoints struct, emit the
// descriptor, the codec, and the Python binding. Runs at build time.
#include <boost/pfr.hpp>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "widgets/widgets.hpp"

namespace {
using nlohmann::ordered_json;

template <class F>
struct traits {
  static constexpr const char* dir = F::dir;
  static constexpr const char* kind = F::kind::name;
  static constexpr const char* discipline = F::discipline::name;
};

struct outputs {
  std::filesystem::path dir;
  std::string cxx = "// GENERATED by syg_generator (ABI-1) — do not edit\n"
                    "#pragma once\n#include <nlohmann/json.hpp>\n"
                    "#include <stdexcept>\n#include \"widgets/widgets.hpp\"\n"
                    "namespace syg::generated {\n";
  std::string py = "# GENERATED by syg_generator (ABI-1) — do not edit\n"
                   "from dataclasses import dataclass\n\nPORTS = {}\n";
};

template <class T>
void emit(outputs& o, const std::string& name) {
  constexpr auto names = boost::pfr::names_as_array<T>();
  T sample{};
  ordered_json ports;
  std::vector<std::string> ins;
  boost::pfr::for_each_field(sample, [&](auto& f, auto i) {
    using F = std::remove_cvref_t<decltype(f)>;
    std::string fname(names[i]);
    ports[fname] = {{"dir", traits<F>::dir},
                    {"kind", traits<F>::kind},
                    {"discipline", traits<F>::discipline}};
    if (std::string(traits<F>::dir) == "in") ins.push_back(fname);
  });
  std::ofstream(o.dir / (name + ".descriptor.json"))
      << ordered_json{{"type", name}, {"ports", ports}}.dump(1) << "\n";

  // codec: the settable at-rest face is the in-ports
  o.cxx += "inline nlohmann::json to_projection(const syg::nodes::" + name + "& x) {\n  return {";
  for (const auto& f : ins) o.cxx += "{\"" + f + "\", x." + f + ".v}, ";
  o.cxx += "};\n}\ninline void from_projection(const nlohmann::json& j, syg::nodes::" +
           name + "& x) {\n  for (const auto& [k, v] : j.items()) {\n";
  for (const auto& f : ins)
    o.cxx += "    if (k == \"" + f + "\") { x." + f + ".v = v; continue; }\n";
  o.cxx += "    throw std::runtime_error(\"" + name + " has no in-port '\" + k + \"'\");\n  }\n}\n";

  // binding: a dataclass that cannot rot
  o.py += "\nPORTS[\"" + name + "\"] = " + ports.dump() + "\n\n@dataclass\nclass " + name + ":\n";
  for (const auto& f : ins) o.py += "    " + f + ": float = 0.0\n";
  o.py += "    def to_projection(self):\n        return {";
  for (const auto& f : ins) o.py += "\"" + f + "\": self." + f + ", ";
  std::string in_set = "{";
  for (const auto& f : ins) in_set += "\"" + f + "\", ";
  in_set += "}";
  o.py += "}\n    @classmethod\n    def from_projection(cls, j):\n"
          "        unknown = set(j) - " + in_set + "\n"
          "        if unknown:\n            raise ValueError(f\"" + name +
          " has no in-port {unknown}\")\n        return cls(**j)\n";
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2) return 1;
  outputs o{argv[1]};
  std::filesystem::create_directories(o.dir);
  emit<syg::nodes::widget_a>(o, "widget_a");
  emit<syg::nodes::widget_b>(o, "widget_b");
  o.cxx += "}  // namespace syg::generated\n";
  std::ofstream(o.dir / "codecs.hpp") << o.cxx;
  std::ofstream(o.dir / "bindings.py") << o.py;
  return 0;
}
