// The generator (ABI-1, AUT-3): reflect each endpoints struct, emit the
// descriptor, the codec, and the Python binding. Runs at build time.
#include <boost/pfr.hpp>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "hello_natives/endpoints.hpp"
#include "testnodes/testnodes.hpp"
#include "widgets/widgets.hpp"

namespace {
using nlohmann::ordered_json;

// Python-side field spelling: keywords get a trailing underscore
inline std::string py_field(const std::string& n) {
  static const std::vector<std::string> kw{
      "in", "for", "if", "else", "not", "and", "or", "is", "import",
      "class", "def", "return", "lambda", "from", "with", "as", "None"};
  for (const auto& k : kw)
    if (n == k) return n + "_";
  return n;
}

template <class F>
struct traits {
  static constexpr const char* dir = F::dir;
  static constexpr const char* kind = F::kind::name;
  static constexpr const char* discipline = F::discipline::name;
};

struct body_flags {
  bool process = false, prepare = false, create = false;
};

struct outputs {
  std::filesystem::path dir;
  std::string shells =
      "// GENERATED by syg_generator (ABI-2/3 shells) — do not edit\n"
      "#pragma once\n#include \"codecs.hpp\"\n#include \"phase.hpp\"\n"
      "#include \"testnodes/testnodes.hpp\"\nnamespace syg::generated {\n"
      "using fault_sink = void (*)(void*, const char* route, const char* what);\n";
  std::string cxx = "// GENERATED by syg_generator (ABI-1) — do not edit\n"
                    "#pragma once\n#include <nlohmann/json.hpp>\n"
                    "#include <stdexcept>\n#include \"hello_natives/endpoints.hpp\"\n"
                    "#include \"testnodes/testnodes.hpp\"\n"
                    "#include \"widgets/widgets.hpp\"\n"
                    "namespace syg::generated {\n";
  std::string py = "# GENERATED by syg_generator (ABI-1) — do not edit\n"
                   "from dataclasses import dataclass\n\nPORTS = {}\n";
  std::string ports_hpp =
      "// GENERATED by syg_generator (AUT-3) — port tables with promises\n"
      "#pragma once\n#include \"crown.hpp\"\nnamespace syg::generated {\n";
};

template <class T>
void emit(outputs& o, const std::string& name, body_flags body = {},
          const std::string& ns = "syg::nodes") {
  constexpr auto names = boost::pfr::names_as_array<T>();
  T sample{};
  ordered_json ports;
  std::vector<std::string> ins;
  boost::pfr::for_each_field(sample, [&](auto& f, auto i) {
    using F = std::remove_cvref_t<decltype(f)>;
    std::string fname(names[i]);
    ports[fname] = {{"dir", traits<F>::dir},
                    {"kind", traits<F>::kind},
                    {"discipline", traits<F>::discipline}};
    if (std::string(traits<F>::dir) == "in") ins.push_back(fname);
  });
  // port tables for the registration layer (no hand-maintained descriptors)
  o.ports_hpp += "inline const std::vector<syg::crown::port_decl>& " + name + "_in_ports() {\n  static const std::vector<syg::crown::port_decl> v{";
  for (const auto& [pn, pv] : ports.items())
    if (pv["dir"] == "in")
      o.ports_hpp += "{\"" + pn + "\", \"" + std::string(pv["kind"]) + "\", \"" +
                     std::string(pv["discipline"]) + "\"}, ";
  o.ports_hpp += "};\n  return v;\n}\ninline const std::vector<syg::crown::port_decl>& " + name + "_out_ports() {\n  static const std::vector<syg::crown::port_decl> v{";
  for (const auto& [pn, pv] : ports.items())
    if (pv["dir"] == "out")
      o.ports_hpp += "{\"" + pn + "\", \"" + std::string(pv["kind"]) + "\", \"" +
                     std::string(pv["discipline"]) + "\"}, ";
  o.ports_hpp += "};\n  return v;\n}\n";

  bool fallible = false;
  for (const auto& [pn, pv] : ports.items())
    if (pv["kind"] == "fault" && pv["dir"] == "out") fallible = true;
  std::ofstream(o.dir / (name + ".descriptor.json"))
      << ordered_json{{"type", name}, {"ports", ports}}.dump(1) << "\n";

  // codec: the settable at-rest face is the in-ports
  o.cxx += "inline nlohmann::json to_projection(const " + ns + "::" + name +
           "& x) {\n  (void)x;\n  return {";
  for (const auto& f : ins) o.cxx += "{\"" + f + "\", x." + f + ".v}, ";
  o.cxx += "};\n}\ninline void from_projection(const nlohmann::json& j, " + ns + "::" +
           name + "& x) {\n  (void)x;\n  for (const auto& [k, v] : j.items()) {\n";
  for (const auto& f : ins)
    o.cxx += "    if (k == \"" + f + "\") { x." + f + ".v = v; continue; }\n";
  o.cxx += "    throw std::runtime_error(\"" + name + " has no in-port '\" + k + \"'\");\n  }\n}\n";

  // binding: a dataclass that cannot rot
  o.py += "\nPORTS[\"" + name + "\"] = " + ports.dump() + "\n\n@dataclass\nclass " + name + ":\n";
  for (const auto& f : ins) o.py += "    " + py_field(f) + ": float = 0.0\n";
  o.py += "    def to_projection(self):\n        return {";
  for (const auto& f : ins) o.py += "\"" + f + "\": self." + py_field(f) + ", ";
  // shells (ch. 13): the hook table adapters — authors never write these
  if (body.process || body.prepare || body.create) {
    const std::string st = name + "_state", qual = ns + "::" + name;
    o.shells += "struct " + st + " { " + qual + " endpoints; const char* route = \"\";"
                " fault_sink emit_fault = nullptr; void* fault_ctx = nullptr; };\n";
    o.shells += "inline void* " + name + "_shell_create() {\n"
                "  syg::abi::phase_guard g(syg::abi::phase::create);\n" +
                (body.create ? "  syg::nodes::" + name + "_create_body();\n" : "") +
                "  return new " + st + "();\n}\n";
    o.shells += "inline void " + name + "_shell_prepare(void*, int rate, int max_block) {\n"
                "  syg::abi::phase_guard g(syg::abi::phase::prepare);\n" +
                (body.prepare ? "  syg::nodes::" + name + "_prepare_body(rate, max_block);\n"
                              : "  (void)rate; (void)max_block;\n") + "}\n";
    o.shells += "inline void " + name + "_shell_apply(void* s, const nlohmann::json& ev) {\n"
                "  syg::abi::phase_guard g(syg::abi::phase::apply);\n"
                "  from_projection(ev, static_cast<" + st + "*>(s)->endpoints);\n}\n";
    if (body.process) {
      o.shells += "inline void " + name + "_shell_process(void* s, const float* const* in,"
                  " float* const* out, int n) noexcept {\n"
                  "  syg::abi::phase_guard g(syg::abi::phase::process);\n";
      if (fallible)  // ONLY declared-fallible shells contain a catch (ABI-3)
        o.shells += "  auto& x = *static_cast<" + st + "*>(s);\n"
                    "  try {\n    syg::nodes::" + name + "_body(in[0], out[0], n);\n"
                    "  } catch (const std::exception& e) {\n"
                    "    if (x.emit_fault) x.emit_fault(x.fault_ctx, x.route, e.what());\n  }\n";
      else
        o.shells += "  (void)s;\n  syg::nodes::" + name + "_body(in[0], out[0], n);\n";
      o.shells += "}\n";
    }
    o.shells += "inline void " + name + "_shell_destroy(void* s) {\n"
                "  syg::abi::phase_guard g(syg::abi::phase::destroy);\n"
                "  delete static_cast<" + st + "*>(s);\n}\n";
  }

  std::string in_set = "{";
  for (const auto& f : ins) in_set += "\"" + f + "\", ";
  in_set += "}";
  o.py += "}\n    @classmethod\n    def from_projection(cls, j):\n"
          "        unknown = set(j) - " + in_set + "\n"
          "        if unknown:\n            raise ValueError(f\"" + name +
          " has no in-port {unknown}\")\n"
          "        import keyword\n"
          "        return cls(**{k + \"_\" if keyword.iskeyword(k) else k: v\n"
          "                      for k, v in j.items()})\n";
}

}  // namespace

void emit_registration(const std::filesystem::path& dir) {
  // SZ-2: natives are present by LINKAGE — this TU references each native's
  // symbol, so a deleted object is a loud link error naming it, and the
  // palette equals this manifest by construction.
  const std::vector<std::string> natives{"osc", "lfo", "vca", "dac", "noise", "add", "cell", "scale", "delay", "pulse", "spectro", "button", "counter", "smoother", "spanv", "mix", "instanced_draw", "nan_bomb", "spin", "sleeper"};
  const std::vector<std::string> organ_natives{
      "parser", "naive_resolver", "registry-face", "slot", "supervisor",
      "graph_source"};
  auto sym = [](std::string n) {
    for (auto& c : n)
      if (c == '-') c = '_';
    return n;
  };
  std::string tu =
      "// GENERATED by syg_generator — the per-target registration TU (SZ-2)\n"
      "#include \"crown.hpp\"\n#include \"registry_face/registry_face.hpp\"\n"
      "namespace syg::nodes {\n";
  for (const auto& n : natives)
    tu += "extern const syg::crown::native_type " + sym(n) + "_native;\n";
  tu += "}\nnamespace syg::organs {\n";
  for (const auto& n : organ_natives)
    tu += "extern const syg::crown::native_type " + sym(n) + "_native;\n";
  tu += "const std::vector<const syg::crown::native_type*>& registered_natives() {\n"
        "  static const std::vector<const syg::crown::native_type*> all{";
  for (const auto& n : natives) tu += "&syg::nodes::" + sym(n) + "_native, ";
  for (const auto& n : organ_natives) tu += "&syg::organs::" + sym(n) + "_native, ";
  tu += "};\n  return all;\n}\n}  // namespace syg::organs\n";
  std::ofstream(dir / "registration.cpp") << tu;
  ordered_json manifest = natives;
  for (const auto& n : organ_natives) manifest.push_back(n);
  std::ofstream(dir / "registration.json") << manifest.dump() << "\n";
}

int main(int argc, char** argv) {
  if (argc < 2) return 1;
  outputs o{argv[1]};
  std::filesystem::create_directories(o.dir);
  emit_registration(o.dir);
  emit<syg::nodes::decl::osc>(o, "osc", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::lfo>(o, "lfo", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::vca>(o, "vca", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::dac>(o, "dac", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::noise>(o, "noise", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::add>(o, "add", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::nan_bomb>(o, "nan_bomb", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::spin>(o, "spin", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::sleeper>(o, "sleeper", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::spanv>(o, "spanv", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::mix>(o, "mix", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::instanced_draw>(o, "instanced_draw", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::graph_source>(o, "graph_source", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::smoother>(o, "smoother", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::button>(o, "button", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::counter>(o, "counter", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::delay>(o, "delay", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::pulse>(o, "pulse", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::spectro>(o, "spectro", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::cell>(o, "cell", {}, "syg::nodes::decl");
  emit<syg::nodes::decl::scale>(o, "scale", {}, "syg::nodes::decl");
  emit<syg::nodes::widget_a>(o, "widget_a");
  emit<syg::nodes::widget_b>(o, "widget_b");
  emit<syg::nodes::parsey>(o, "parsey", {.process = true});
  emit<syg::nodes::boom>(o, "boom", {.process = true});
  emit<syg::nodes::devicey>(o, "devicey", {.prepare = true});
  emit<syg::nodes::devicey_bad>(o, "devicey_bad", {.create = true});
  o.cxx += "}  // namespace syg::generated\n";
  std::ofstream(o.dir / "codecs.hpp") << o.cxx;
  o.shells += "}  // namespace syg::generated\n";
  std::ofstream(o.dir / "shells.hpp") << o.shells;
  o.ports_hpp += "}  // namespace syg::generated\n";
  std::ofstream(o.dir / "native_ports.hpp") << o.ports_hpp;
  std::ofstream(o.dir / "bindings.py") << o.py;
  return 0;
}
